flags: {}
packages:
- '.'
- location:
    git: https://github.com/jaspervdj/hakyll.git
    commit: 3c73cd1e32e3070924abf542c456c67d778e0b27
- location:
    git: https://github.com/isovector/circuitry.git
    commit: 320aef8a27e498d5c3df96c94563ec82c53290b3
extra-deps:
- hakyll-4.9.0.0
- datetime-0.3.1
- strptime-1.0.10
- mfsolve-0.3.2.0
- here-1.2.9
resolver: lts-7.1
