flags: {}
packages:
- '.'
extra-deps:
    - hakyll-4.6.9.0
    - parsec-3.1.9
    - datetime-0.3.1
    - containers-0.5.5.1
    - pandoc-1.13.2.1
    - filepath-1.3.0.2
    - time-1.4.2
    - old-locale-1.0.0.6
    - strptime-1.0.10
resolver: lts-2.17
