flags: {}
packages:
- '.'
- location:
    git: https://github.com/jaspervdj/hakyll.git
    commit: 3c73cd1e32e3070924abf542c456c67d778e0b27
extra-deps:
- hakyll-4.9.0.0
- datetime-0.3.1
- strptime-1.0.10
resolver: lts-7.3
